//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cactusiki.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contracts
    {
        public int number_Contract { get; set; }
        public Nullable<int> Exhibition_id { get; set; }
        public Nullable<int> Cactus_id { get; set; }
        public string Reward { get; set; }
        public string Comments { get; set; }
    
        public virtual Cactus Cactus { get; set; }
        public virtual Exhibitions Exhibitions { get; set; }
    }
}
