//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cactusiki.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class Street
    {
        public int kod_Street { get; set; }
        public string Name { get; set; }
        public Nullable<int> City_id { get; set; }
    
        public virtual City City { get; set; }
    }
}
